#import "RNWalkMeSdk.h"

#ifdef RCT_NEW_ARCH_ENABLED
// Generated by React Native Codegen from `src/NativeWalkMeSdk.ts` (see
// `codegenConfig` in package.json). Under CocoaPods the artifacts are produced
// into the `ReactCodegen` pod during `pod install` / the "Generate Specs" build
// phase, which is why this header is never checked in.
#import <WalkMeSdkSpec/WalkMeSdkSpec.h>
#endif

// Objective-C interface generated for `ios/Sources/Shared/WalkMeSdkProvider.swift`.
// The pod is named `walkme-react-native-sdk`, so its Swift module — and hence the
// generated header — is `walkme_react_native_sdk`. The angle-bracket form is used
// when the pod is built as a framework (`use_frameworks!`), the quoted form for
// the default static-library integration.
#if __has_include(<walkme_react_native_sdk/walkme_react_native_sdk-Swift.h>)
#import <walkme_react_native_sdk/walkme_react_native_sdk-Swift.h>
#else
#import "walkme_react_native_sdk-Swift.h"
#endif

@implementation RNWalkMeSdk

RCT_EXPORT_MODULE()

+ (BOOL)requiresMainQueueSetup
{
  return NO;
}

/**
 * Unchanged from previous releases. Note that `walkme_item_action` is
 * deliberately absent: the WalkMe iOS SDK's `WMItemCallbacksDelegate` has no
 * item-action callback, so iOS has never emitted that event. Android does.
 */
- (NSArray<NSString *> *)supportedEvents
{
  return @[ @"walkme_item_presented", @"walkme_item_dismissed", @"walkme_analytics_event" ];
}

#pragma mark - Lifecycle

RCT_EXPORT_METHOD(start:(NSDictionary *)options)
{
  dispatch_async(dispatch_get_main_queue(), ^{
    [WMRNSdkProvider start:options];
  });
}

RCT_EXPORT_METHOD(stop)
{
  [WMRNSdkProvider stop];
}

RCT_EXPORT_METHOD(restart)
{
  [WMRNSdkProvider restart];
}

#pragma mark - Items

RCT_EXPORT_METHOD(startItemByID:(double)itemId deepLink:(nullable NSString *)deepLink)
{
  [WMRNSdkProvider startItemByID:(NSInteger)itemId deepLink:deepLink];
}

RCT_EXPORT_METHOD(dismissItem)
{
  [WMRNSdkProvider dismissItem];
}

#pragma mark - User / content

RCT_EXPORT_METHOD(setUserId:(nullable NSString *)userId)
{
  [WMRNSdkProvider setUserId:userId];
}

RCT_EXPORT_METHOD(setVariable:(NSString *)key value:(nullable NSString *)value)
{
  [WMRNSdkProvider setVariable:key value:value];
}

RCT_EXPORT_METHOD(setEventUserVars:(NSDictionary *)vars)
{
  [WMRNSdkProvider setEventUserVars:vars];
}

RCT_EXPORT_METHOD(setLanguage:(NSString *)language)
{
  [WMRNSdkProvider setLanguage:language];
}

RCT_EXPORT_METHOD(sendEvent:(NSString *)name attributes:(nullable NSDictionary *)attributes)
{
  [WMRNSdkProvider sendEvent:name attributes:attributes];
}

#pragma mark - Callbacks

/**
 * Dispatched to main so this runs AFTER start()'s queued block on the same
 * serial queue. Otherwise this runs synchronously before start() and the
 * delegate is dropped when start() initializes the SDK.
 */
RCT_EXPORT_METHOD(setItemInfoListener:(BOOL)enable)
{
  __weak RNWalkMeSdk *weakSelf = self;
  dispatch_async(dispatch_get_main_queue(), ^{
    if (!enable) {
      [WMRNSdkProvider setItemInfoHandler:nil];
      return;
    }
    [WMRNSdkProvider setItemInfoHandler:^(NSString *eventName, NSDictionary *body) {
      [weakSelf sendEventWithName:eventName body:body];
    }];
  });
}

/** See `setItemInfoListener:` — same ordering requirement relative to `start`. */
RCT_EXPORT_METHOD(setAnalyticsListener:(BOOL)enable)
{
  __weak RNWalkMeSdk *weakSelf = self;
  dispatch_async(dispatch_get_main_queue(), ^{
    if (!enable) {
      [WMRNSdkProvider setAnalyticsHandler:nil];
      return;
    }
    [WMRNSdkProvider setAnalyticsHandler:^(NSDictionary *body) {
      [weakSelf sendEventWithName:@"walkme_analytics_event" body:body];
    }];
  });
}

#pragma mark - Teardown

/**
 * A React instance reload deallocates this module but not the WalkMe SDK
 * singleton, which would otherwise keep invoking a handler that captures a dead
 * emitter. Mirrors `WalkMeSdkBridge.invalidate()` on Android.
 */
- (void)invalidate
{
  dispatch_async(dispatch_get_main_queue(), ^{
    [WMRNSdkProvider setItemInfoHandler:nil];
    [WMRNSdkProvider setAnalyticsHandler:nil];
  });
  [super invalidate];
}

#pragma mark - TurboModule

#ifdef RCT_NEW_ARCH_ENABLED
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeWalkMeSdkSpecJSI>(params);
}
#endif

@end
