package com.walkme.rn

/**
 * New Architecture base class for [RNWalkMeSdkModule].
 *
 * `NativeWalkMeSdkSpec` is generated by React Native Codegen from
 * `src/NativeWalkMeSdk.ts` into `build/generated/source/codegen/java`; see the
 * `react { }` block in `android/build.gradle`. Aliasing it here keeps
 * `android/src/main/java/com/walkme/rn/RNWalkMeSdkModule.kt` identical across
 * both architectures.
 *
 * This has to be a `typealias` rather than a wrapper subclass: both
 * `JavaModuleWrapper.findMethods()` and `TurboModuleInteropUtils` only treat a
 * module as spec-based when its *direct* superclass implements `TurboModule`.
 */
typealias RNWalkMeSdkSpec = NativeWalkMeSdkSpec
